name: Build & Deploy – Azure Function reco-p10

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  APP_PATH: 'azure_function'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.APP_PATH }}/requirements.txt

      - name: Create deployment package
        # on se place DANS azure_function pour zipper son contenu
        working-directory: ${{ env.APP_PATH }}
        run: |
          zip -r ../function.zip . \
            -x "__pycache__/**" "venv/**"

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: function-package
          path: function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: function-package

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_085B4AA212A640A09423F47D7B323905 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7044A94E284E48A783BF711B11BDC35C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E66DFBFAB21471CABDB49E2B80AEF48 }}

      - name: Deploy to Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'reco-p10'
          package: function.zip
