name: Build & Deploy – Azure Function reco‑p10

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'        # runtime choisi dans la Function App
  APP_PATH: 'azure_function'    # dossier qui contient host.json + code

# ───────────────────────────────────────────────────────────────
# 1) BUILD  ➜  produit function.zip
# ───────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (optionnel – tests/lint)
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.APP_PATH }}/requirements.txt

      # (insère ici tes tests unitaires éventuels)

      - name: Créer l’archive de déploiement
        run: |
          zip -r function.zip ${{ env.APP_PATH }} \
              -x "**/__pycache__/**" "**/venv/**"

      - name: Publier l’artefact
        uses: actions/upload-artifact@v4
        with:
          name: function-package
          path: function.zip

# ───────────────────────────────────────────────────────────────
# 2) DEPLOY  ➜  envoie function.zip dans la Function App
# ───────────────────────────────────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # OIDC / RBAC
      contents: read

    steps:
      - name: Récupérer l’archive
        uses: actions/download-artifact@v4
        with:
          name: function-package

      - name: Login Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_085B4AA212A640A09423F47D7B323905 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7044A94E284E48A783BF711B11BDC35C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E66DFBFAB21471CABDB49E2B80AEF48 }}

      - name: Déployer vers Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:  'reco-p10'          # nom exact de la Function App
          slot-name: 'Production'
          package:   function.zip        # le zip extrait juste au‑dessus
