name: Build & Deploy – Azure Function reco-p10

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  APP_PATH: 'azure_function'    # dossier qui contient host.json + function_app.py + requirements.txt

jobs:
  # ───────────────────────────────────────────────────────────────
  # 1) BUILD  ➜  installe les deps dans APP_PATH (pour que func-action puisse
  #              scanner les triggers et créer function.json automatiquement)
  # ───────────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.APP_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # ───────────────────────────────────────────────────────────────
  # 2) DEPLOY  ➜  envoie directement tout le dossier azure_function
  # ───────────────────────────────────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_085B4AA212A640A09423F47D7B323905 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7044A94E284E48A783BF711B11BDC35C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E66DFBFAB21471CABDB49E2B80AEF48 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'reco-p10'
          package: '${{ env.APP_PATH }}'
          # note: on n’a plus besoin du slot ni du zip explicite
