name: Build & Deploy – Azure Function reco-p10

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  APP_PATH: "azure_function"    # dossier qui contient host.json + function_app.py

jobs:
  # ───────────────────────────────────────────────────────────
  # 1) BUILD → génère function.zip
  # ───────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read             # pour actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (facultatif pour tests)
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.APP_PATH }}/requirements.txt

      - name: Create deployment archive
        run: |
          cd ${{ env.APP_PATH }}
          zip -r ../function.zip . -x "**/__pycache__/**" "**/venv/**"

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-package
          path: function.zip

  # ───────────────────────────────────────────────────────────
  # 2) DEPLOY → publie function.zip dans la Function App
  # ───────────────────────────────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write            # pour OIDC Azure
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-package

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_085B4AA212A640A09423F47D7B323905 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7044A94E284E48A783BF711B11BDC35C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E66DFBFAB21471CABDB49E2B80AEF48 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:  "reco-p10"
          slot-name: "Production"
          package:   "function.zip"
