# Build and deploy Python project to Azure Function App - reco-p10
# ===============================================================
# • Ne déploie que le dossier azure_function (où se trouvent host.json, function_app.py, etc.)
# • Installe ses dépendances depuis azure_function/requirements.txt
# • Utilise Python 3.10
# • Authentification Azure : secrets créés par le portail (Publish profile → “Deploy to GitHub Actions”)

name: Build and deploy Python project to Azure Function App - reco-p10

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./azure_function   # dossier à déployer
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read                # pour actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Azure Function dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r azure_function/requirements.txt

      # (ajoutez ici vos tests éventuels)

      - name: Zip Azure Function folder
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write               # requis pour azure/login OIDC
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip -o release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZUREAPPSERVICE_CLIENTID_085B4AA212A640A09423F47D7B323905 }}
          tenant-id:      ${{ secrets.AZUREAPPSERVICE_TENANTID_7044A94E284E48A783BF711B11BDC35C }}
            subscription-id:${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E66DFBFAB21471CABDB49E2B80AEF48 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: reco-p10
          slot-name: Production
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
