# .github/workflows/master_reco-p10.yml
name: Build & Deploy – Azure Function reco-p10

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  APP_DIR: 'azure_function'   # dossier racine de votre Function App

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.APP_DIR }}/requirements.txt

      - name: Package Function App
        run: |
          cd ${{ env.APP_DIR }}
          zip -r ../function.zip . \
            -x "venv/**" "__pycache__/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-package
          path: function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_085B4AA212A640A09423F47D7B323905 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7044A94E284E48A783BF711B11BDC35C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E66DFBFAB21471CABDB49E2B80AEF48 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'reco-p10'
          package: 'function.zip'
